In [2]:
import pandas as pd
import requests
import time

In [3]:
unemp_data=pd.read_csv("unemp_rate.csv")
unemp_data
unemp_data.set_index('Date',inplace=True)
unemp_data

,Unemp_Hispanic,Unemp_Asian,Unemp_Black,Unemp_White,Unemp_Civilian,Unemp_Men,Unemp_Women,Unemp_White_Men,20-24,25-34,35-44,45-54,55 and up,"Unemp (>25, less than HS)","Unemp (>25, HS)","Unemp (>25, College)","Unemp (>25, Master)","Unemp (>25, Doctoral)"
Date,,,,,,,,,,,,,,,,,,
2021-03-01,7.9,5.9,9.6,5.4,6.0,6.2,5.9,3.348,10.3,6.7,5.1,4.5,4.5,8.2,6.7,3.7,3.6,1.6
2021-02-01,8.5,5.1,9.9,5.6,6.2,6.3,6.1,3.528,9.6,6.4,5.7,4.9,5.3,10.1,7.2,3.8,3.6,1.6
2021-01-01,8.6,6.8,9.2,5.7,6.3,6.4,6.3,3.648,9.7,6.8,5.7,4.9,5.3,9.1,7.1,4.0,3.7,2.3
2020-12-01,9.3,5.8,9.9,6.0,6.7,6.7,6.7,4.020,11.2,6.6,5.5,5.3,6.0,9.8,7.8,3.8,3.5,1.4
2020-11-01,8.4,6.7,10.3,5.9,6.7,6.9,6.4,4.071,10.7,7.0,5.6,5.5,5.8,9.2,7.8,4.2,3.5,1.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1948-05-01,NaN,NaN,NaN,NaN,3.5,3.5,3.7,NaN,6.6,3.0,2.6,2.4,3.1,NaN,NaN,NaN,NaN,NaN
1948-04-01,NaN,NaN,NaN,NaN,3.9,3.8,4.3,NaN,6.8,3.4,2.9,2.6,3.0,NaN,NaN,NaN,NaN,NaN
1948-03-01,NaN,NaN,NaN,NaN,4.0,3.8,4.4,NaN,7.6,2.9,2.7,2.6,3.0,NaN,NaN,NaN,NaN,NaN
1948-02-01,NaN,NaN,NaN,NaN,3.8,3.6,4.5,NaN,6.3,3.3,2.5,2.8,3.1,NaN,NaN,NaN,NaN,NaN
1948-01-01,NaN,NaN,NaN,NaN,3.4,3.4,3.3,NaN,5.8,3.0,2.0,2.2,2.9,NaN,NaN,NaN,NaN,NaN